### ISSUE TITLE
Ticking entity I java.lang.ClassCastException

### ISSUE THREAD

**Issue by TheButterbrotMan** [CartoonishVillain/CarryTheNametag-Fabric#1]
https://bytebin.lucko.me/xKXd5XDqgH

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/IBL5L46PQc

**Comment by TheButterbrotMan** [comment]
https://github.com/CrimsonFluff/Crimson-Chickens/issues/45

**Comment by CartoonishVillain** [comment]
Crash acknowledged. Will look into when I am off work

**Comment by ghost** [comment]
Hi, im having trouble tracking this, mainly because your project says its using yarn 1.17.1 ? for the 1.18 fabric version

so I cant load the `Animal.class` class to see whats happening.  I override `createChild` but im not sure this is the same as your mixin for `spawnChildFromBreeding`

do you know if/how I can import your project into my dev workspace?  I dont know what to add to the gradle to make this possible

**Comment by ghost** [comment]
and now for the kicker: I just renamed 2 chickens and bred them fine, no errors, no crashes. 3 times. both named, and only 1 named

**Comment by CartoonishVillain** [comment]
You should be able to import it with cursemaven. 

Yes I do technically use Yarn 1.17, mostly because I never updated it since I use mojmaps. Wasn't aware that could cause an issue, still new to the whole fabric thing, my apologies 😅 

I do also apologize but as mentioned prior I have work to tend to. I won't be much of help for another 9 hours or so aside from answering questions on occasion. 

If I had to take a wild stab in the dark I'd say wherever the method in the crashlog leads I probably did a dumb cast that causes a problem

**Comment by CartoonishVillain** [comment]
Investigating further, the crash reports are complaining about a cast between an animal's name and casting it to be a TextComponent.

I have absolutely no idea where a mob could have a name that isn't convertible to a Text Component, but I suppose our answer was found in this crash report.

I have placed the assignment in these in a try catch block. If it tries to crash like that again, it should just peacefully stop trying to name the mob. 

When this ticket closes, the patch for this is out. Thank you for reporting!

**Comment by ghost** [comment]
Its all good. Im new to modding in general with both Forge and Fabric.  Ive got maven working for Forge but not sure if its the same for Fabric.  I also notice some modders (like yourself) using Parchment - whatever that is - guess I need to start watching some McJty tutorial videos, lol

But anywho feel free to look at my projects on github - they may not be correct - but they work, lolz

**Comment by CartoonishVillain** [comment]
I personally use mojmaps/parchment (loom.officialmappings or something to the tune of it) (I personally haven't moved to parchment myself, but it's _basically_ just mojmaps with extra cool stuff as far as I know) because it makes porting between forge and fabric easier w/o using templates and the like. Most class files can be more or less copied and pasted over. Forge uses the same mappings by default
